services:

    register_user_handler:
        class: Traditional\Bundle\UserBundle\Command\RegisterUserHandler
        arguments:
            doctrine: "@doctrine"
            eventRecorder: "@event_recorder"
        tags:
            - { name: command_handler, handles: register_user }

    when_user_was_registered_send_welcome_email:
        class: Traditional\Bundle\UserBundle\Event\WhenUserWasRegisteredSendWelcomeEmail
        arguments:
            mailer: "@mailer"
        tags:
            - { name: event_subscriber, subscribes_to: user_was_registered }

